version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.3.0"
    working_directory: /Users/distiller/project

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: swift test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
